name: Deploy Showcase

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: packages/eventhub-showcase/package-lock.json

      - name: Install dependencies and build
        working-directory: packages/eventhub-showcase
        run: |
          echo "Instalando solo en directorio showcase"
          cp package.json package.json.backup
          sed -i 's/"name": "eventhub-showcase"/"name": "showcase"/g' package.json
          rm -f package-lock.json
          npm install --no-package-lock --legacy-peer-deps
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/eventhub-showcase/dist 