name: Deploy to GitHub Pages

on:
  # Ejecutar en cada push al branch main
  push:
    branches: [main]
  # Permite ejecutar manualmente desde la pestaña Actions
  workflow_dispatch:

# Permitir que este job clone el repositorio y cree un despliegue de páginas
permissions:
  contents: read
  pages: write
  id-token: write

# Permitir solo un deploy concurrente
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        
      - name: Copy showcase files to temp directory
        run: |
          mkdir -p /tmp/showcase
          cp -r packages/eventhub-showcase/* /tmp/showcase/
          cd /tmp/showcase
          
      - name: Install dependencies
        run: |
          cd /tmp/showcase
          npm install
          
      - name: Build showcase
        run: |
          cd /tmp/showcase
          npm run build
          
      - name: Create .nojekyll file
        run: |
          cd /tmp/showcase/dist
          touch .nojekyll
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /tmp/showcase/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 