name: Deploy to GitHub Pages

on:
  # Ejecutar en cada push al branch main
  push:
    branches: [main]
  # Permite ejecutar manualmente desde la pestaña Actions
  workflow_dispatch:

# Permitir que este job clone el repositorio y cree un despliegue de páginas
permissions:
  contents: read
  pages: write
  id-token: write

# Permitir solo un deploy concurrente
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        run: cd packages/eventhub-showcase && npm ci
      - name: Build
        run: cd packages/eventhub-showcase && npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./packages/eventhub-showcase/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 